### ISSUE TITLE
Report query: Overdue and lost 

### ISSUE THREAD

**Issue by kristenwilson** [openlibraryenvironment/reshare-analytics#9]
Report of all requests where the due date has passed and the state is not "Complete." 

Report mockup: https://docs.google.com/spreadsheets/d/1KgfneTJZAQGow_87_Mra-xGqsAi9AmtWVnS0ph4VO4Y/edit#gid=0

**Comment by kristenwilson** [comment]
At the June 9 meeting, we clarified that having requests with an "overdue" status is not required to begin working on this report. The query will select all requests where the due date has passed and the state is not "complete." At the moment, there are still no overdue requests in the test system, but I will continue to work on getting some in. I think there is bug interfering with this.

**Comment by riyaku11** [comment]
I would like to work on this issue

**Comment by scwiek** [comment]
https://github.com/openlibraryenvironment/reshare-analytics/commit/c0efa8be727bca63b436cc3765f369a3c8d418a9
